export const enum Actions {
  GET_GAMES = 'GET_GAMES',
  SET_GAMES = 'SET_GAMES',
  GET_PROVIDERS = 'GET_PROVIDERS',
  SET_PROVIDERS = 'SET_PROVIDERS',
  SET_FILTERS = 'SET_FILTERS',
  UPDATE_PAGE = 'UPDATE_PAGE',
  CLEAR_FILTERS = 'CLEAR_FILTERS',
};
